name: Deploy to Staging

on:
  push:
    branches:
      - staging
      - develop
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: react-app/package-lock.json

      - name: Install dependencies
        working-directory: react-app
        run: npm ci

      - name: Run lint
        working-directory: react-app
        run: npm run lint -- --max-warnings 0
        continue-on-error: true

      - name: Run type check
        working-directory: react-app
        run: npx tsc --noEmit
        continue-on-error: true

      - name: Build project
        working-directory: react-app
        run: npm run build

      - name: Run tests
        working-directory: react-app
        run: npm test -- --passWithNoTests
        continue-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./react-app
          alias-domains: |
            gplat-staging.vercel.app